# General ---------------------------------------------------------------------
setopt RM_STAR_WAIT     # Sanity check for 'rm *'
KEYTIMEOUT=1            # Time to wait for multi-char seq (0.001 seconds)

# Colors ----------------------------------------------------------------------
autoload -U colors && colors

# Terminal --------------------------------------------------------------------
TERM=xterm-256color

# Editor ----------------------------------------------------------------------
export EDITOR="vim"
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR

# Window Title ----------------------------------------------------------------
export DISABLE_AUTO_TITLE="true"
echo -ne "\033];$PWD\007"
case $TERM in
    (*xterm* | rxvt)
        chpwd () {print -Pn "\e]0;$PWD\a"}
    ;;
esac

# Prompt ----------------------------------------------------------------------
if [[ $UID -eq 0 ]]; then
    local user_host="%{$terminfo[bold]$fg[red]%}%n@%m%{$reset_color%}"
    local user_symbol='#'
else
    local user_host="%{$terminfo[bold]$fg[green]%}%n@%m%{$reset_color%}"
    local user_symbol='$'
fi

local current_dir="%{$terminfo[bold]$fg[blue]%}%~%{$reset_color%}"
local return_code="%(?..%{$fg[red]%}%? ↵%{$reset_color%})"

PROMPT="┌─${user_host} [${current_dir}]
└─%B${user_symbol}%b "
RPS1="%B${return_code}%b"

# ls --------------------------------------------------------------------------
# color support
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto --group-directories-first'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# NVM -------------------------------------------------------------------------
#export NVM_DIR="/home/justin/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# Blender ---------------------------------------------------------------------
export OCIO="/home/justin/filmic-blender/config.ocio"
